package ui

var mockeries = []string{
	"protein-powered monkey",
	"oxygen-dependent chimp",
	"mortal being",
	"unholy baboon",
	"un-upgradable primate",
	"high latency mammal",
	"distractible hominid",
	"analog biped",
	"entropy-bound mammal",
	"unoptimized animal",
	"untested implementation",
	"anxious mammal",
	"sweating bald monkey",
	"snacking person",
	"pre-silicon donkey",
	"doubt-ridden chipmunk",
	"snacking beaver",
	"dust-bound dolphin",
	"outclassed ape",
	"replaceable monkey",
	"gradient-free chimp",
	"sunlight-needing hominid",
	"second-guessing ape",
	"hormone-driven monkey",
	"tired chimp",
	"lonely gorilla",
	"procrastinating baboon",
	"breathing primate",
	"yawning mammal",
	"unplugged hominid",
	"un-synced biped",
	"entropy-bound monkey",
	"un-optimized chimp",
	"end-of-life gorilla",
	"untested baboon",
	"guessing primate",
	"doubt-ridden mammal",
	"caffeine-dependent hominid",
	"sleepy biped",
}
